<a href="https://colab.research.google.com/github/SoniaPMi/Master-IA/blob/main/Basic_LSTM_keras_alumnos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creación de capas LSTM en Keras

In [1]:
import tensorflow as tf
from keras.layers import LSTMCell, LSTM

In [2]:
from numpy.random import seed
seed(1)
tf.random.set_seed(2)

### LSTM a partir de LSTMCell encapsulada en capa RNN

In [3]:
inputs = tf.random.normal([32, 10, 8])
rnn = tf.keras.layers.RNN(tf.keras.layers.LSTMCell(4))
output = rnn(inputs)
print(output.shape)

rnn = tf.keras.layers.RNN(
   tf.keras.layers.LSTMCell(4),
   return_sequences=True,
   return_state=True)
whole_seq_output, final_memory_state, final_carry_state = rnn(inputs)
print(whole_seq_output.shape)

print(final_memory_state.shape)

print(final_carry_state.shape)


(32, 4)
(32, 10, 4)
(32, 4)
(32, 4)


In [7]:
# Determina la salida final (tras 10 time steps) de la LSTM para la muestra 32 
final_memory_state # = whole_seq_output[[-1, -1]]

<tf.Tensor: shape=(32, 4), dtype=float32, numpy=
array([[ 0.51235765,  0.0389048 ,  0.23825817,  0.04272646],
       [-0.3105641 ,  0.14984639,  0.01561201, -0.00965086],
       [ 0.16623373, -0.02401589,  0.1497836 ,  0.26462644],
       [ 0.31531835, -0.10075305,  0.06625727, -0.20350279],
       [ 0.05771682, -0.06550565, -0.26266435,  0.05062744],
       [ 0.11979724, -0.01559168,  0.11800979,  0.08040491],
       [-0.08589976,  0.03652469,  0.07495347,  0.4977028 ],
       [-0.29545403, -0.22342151, -0.2905299 , -0.04680187],
       [ 0.09633102, -0.1572051 ,  0.03566454,  0.17657337],
       [ 0.00560371, -0.34801263, -0.30901277,  0.21385485],
       [-0.07315988, -0.14272395,  0.1342134 , -0.16102947],
       [ 0.05916089,  0.00112796,  0.04582447,  0.41819566],
       [-0.05757838,  0.08819887,  0.20661245,  0.39653993],
       [-0.18027362,  0.13182361,  0.07735182,  0.1015406 ],
       [ 0.161747  , -0.09695955,  0.2582656 , -0.18232803],
       [ 0.19230947,  0.03070229,  0

In [8]:
whole_seq_output[[-1, -1]]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.18213858, 0.08395582, 0.11142362, 0.10321011], dtype=float32)>

In [9]:
# Determina la salida final (tras 10 time steps) de la LSTM para la muestra 15 
whole_seq_output[[15, -1]] #muestra 15, último instante temporal

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.19230947, 0.03070229, 0.09855746, 0.07757574], dtype=float32)>

### LSTM a partir de capa LSTM

In [10]:
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)

lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)
print(whole_seq_output.shape)

print(final_memory_state.shape)

print(final_carry_state.shape) 


(32, 4)
(32, 10, 4)
(32, 4)
(32, 4)


## Integrar la capa LSTM en un modelo

In [11]:
# Import `Sequential` from `keras.models`
from keras.models import Sequential
# Import `Dense` from `keras.layers`
from keras.layers import Dense, LSTM

In [12]:
# Ejemplo: Capa LSTM de 32 salidas (units) conectada a capa densa. 
# En input shape se define el tamaño de entrada: (timesteps, features) 
model = Sequential()
model.add(LSTM(32, input_shape=(50, 2)))
model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 32)                4480      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 4,513
Trainable params: 4,513
Non-trainable params: 0
_________________________________________________________________


### EJERCICIO

Crea una secuencia temporal (np.array) de 10 números reales (10 time steps). Crea un modelo compuesto por una capa LSTM de 4 salidas conectada a una capa densa de 1 neurona. Evalúa la salida del modelo para la secuencia anterior en cada instante de tiempo. Nota: recuerda que LSTM() requiere entradas tridimensionales, aunque tengamos sólo una secuencia. 

- Prueba a poner return_sequences=False. Observa la salida en ese caso.

- Repite el ejercicio pero con un array de 10 time steps y 2 features.

- Apila una segunda capa LSTM de 4 salidas tras la primera y antes de la capa densa. Recuerda que la primera LSTM tiene que tener return_sequences=True. Observa la salida. 


In [21]:
from numpy import array
data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
data = data.reshape((1, 10, 1))
print(data.shape)
data

(1, 10, 1)


array([[[0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9],
        [1. ]]])

In [14]:
model = Sequential()
model.add(LSTM(4, input_shape=(10, 1), return_sequences=True))
model.add(Dense(1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 10, 4)             96        
                                                                 
 dense_1 (Dense)             (None, 10, 1)             5         
                                                                 
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [15]:
out=model(data)

In [16]:
print(out)

tf.Tensor(
[[[0.02745794]
  [0.07269983]
  [0.12938198]
  [0.19319937]
  [0.2611881 ]
  [0.33129418]
  [0.40205154]
  [0.47232255]
  [0.54110163]
  [0.6073975 ]]], shape=(1, 10, 1), dtype=float32)


In [22]:
# Ahora con array de 2 features
data = array ([
               [0.1, 1.0],
               [0.2, 0.9],
               [0.3, 0.8],
               [0.4, 0.7],
               [0.5, 0.6],
               [0.6, 0.5],
               [0.7, 0.4],
               [0.8, 0.3],
               [0.9, 0.2],
               [1.0, 0.1]])

In [23]:
data = data.reshape(1, 10, 2)
print(data.shape)

(1, 10, 2)


In [24]:
model = Sequential()
model.add(LSTM(4, input_shape=(10,2), return_sequences=True))
model.add(Dense(1))

In [25]:
out = model(data)
print(out)

tf.Tensor(
[[[-0.10153613]
  [-0.15904397]
  [-0.18747552]
  [-0.19890827]
  [-0.20085925]
  [-0.19765525]
  [-0.19178797]
  [-0.1847493 ]
  [-0.17745863]
  [-0.17045932]]], shape=(1, 10, 1), dtype=float32)


In [26]:
# Ahora con stacked LSTM de 2 capas
model = Sequential()
model.add(LSTM(4, input_shape=(10,2), return_sequences=True))
model.add(LSTM(4))
model.add(Dense(1))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 10, 4)             112       
                                                                 
 lstm_6 (LSTM)               (None, 4)                 144       
                                                                 
 dense_3 (Dense)             (None, 1)                 5         
                                                                 
Total params: 261
Trainable params: 261
Non-trainable params: 0
_________________________________________________________________


In [27]:
out = model(data)
print(out)

tf.Tensor([[0.00193809]], shape=(1, 1), dtype=float32)
